### ISSUE TITLE
Add some logging to the custom resource lambda

### ISSUE THREAD

**Issue by zendern** [udondan/cdk-ssm-document#24]
## Feature Request

Add some logging of the event that is sent to the lambda as well as the request objects that are sent to the api calls. 

## Reason

When debugging a misconfigured json blob elements `mainSteps` and its' children there are not enough details to understand the failure. 

Current details are only this: 

```
022-02-07T14:07:42.451Z	c7bcb752-d1ba-423c-a527-4d4d64cf1150	ERROR	InvalidDocumentContent: JSON not well-formed. at Line: 1, Column: 610    
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)    
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)    
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)    
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)    
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)    
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)    
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10    
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)    
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)    
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {  code: 'InvalidDocumentContent',  time: 2022-02-07T14:07:42.448Z,  requestId: 'b35ffedf-86ad-4e56-b889-dfe75f290c79',  statusCode: 400,  retryable: false,  retryDelay: 61.14163968992787} InvalidDocumentContent: JSON not well-formed. at Line: 1, Column: 610    
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)    
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)    
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)    
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)   
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)    
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)    
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10   
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)    
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)    
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) 
```

**Comment by udondan** [comment]
I'm going to deprecate this construct. A few weeks ago there was an [update](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ssm/pull/173) to the native CloudFormation resource, which now finally supports updates.
